/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.57
 * Generated at: 2015-04-01 07:52:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class ki_005fwrite_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=EUC-KR\">\r\n");
      out.write("<!-- for icons -->\r\n");
      out.write("<link href=\"//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- google web font -->\r\n");
      out.write("<link href='http://fonts.googleapis.com/css?family=Open+Sans:400;300' rel='stylesheet' type='text/css'>\r\n");
      out.write("\r\n");
      out.write("<!-- jquery -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery-1.11.2.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- jquery plugin -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery.leanModal.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- custom js -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/menu_js.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- custom css -->\r\n");
      out.write("<link href=\"css/menu_css.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tvar inputImage = (function loadImageFile() {\r\n");
      out.write("\t\r\n");
      out.write("\t\tif (window.FileReader) {\r\n");
      out.write("\t\tvar ImagePre;\r\n");
      out.write("\t\tvar ImgReader = new window.FileReader();\r\n");
      out.write("\t\tvar fileType = /^(?:image\\/bmp|image\\/gif|image\\/jpeg|image\\/png|image\\/x\\-xwindowdump|image\\/x\\-portable\\-bitmap)$/i;\r\n");
      out.write("\r\n");
      out.write("\t\tImgReader.onload = function(Event) {\r\n");
      out.write("\t\t\tif (!ImagePre) {\r\n");
      out.write("\t\t\t\tvar newPreview = document.getElementById(\"imagePreview\");\r\n");
      out.write("\t\t\t\tImagePre = new Image();\r\n");
      out.write("\t\t\t\tImagePre.style.width = \"150px\";\r\n");
      out.write("\t\t\t\tImagePre.style.height = \"150px\";\r\n");
      out.write("\t\t\t\tImagePre.style.borderRadius = \"100%\";\r\n");
      out.write("\t\t\t\tnewPreview.appendChild(ImagePre);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tImagePre.src = Event.target.result;\r\n");
      out.write("\r\n");
      out.write("\t\t};\r\n");
      out.write("\r\n");
      out.write("\t\treturn function() {\r\n");
      out.write("\r\n");
      out.write("\t\t\tvar img = document.getElementById(\"image\").files;\r\n");
      out.write("\r\n");
      out.write("\t\t\tif (!fileType.test(img[0].type)) {\r\n");
      out.write("\t\t\t\talert(\"이미지 파일을 업로드 하세요\");\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"image\").value=\"\";\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\tImgReader.readAsDataURL(img[0]);\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("\tdocument.getElementById(\"imagePreview\").src = document.getElementById(\"image\").value;\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("})();\r\n");
      out.write("\r\n");
      out.write("\tfunction writee(f) {\r\n");
      out.write("\t\tif(f.k_kind.value == 0){\r\n");
      out.write("\t\t\talert(\"기 카테고리를 선택해주세요\");\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(f.k_content.value == \"\"){\r\n");
      out.write("\t\t\talert(\"글 내용을 입력하세요\");\r\n");
      out.write("\t\t\tf.k_content.focus();\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(f.k_max.value == \"\"){\r\n");
      out.write("\t\t\talert(\"기 개수를 입력하세요\");\r\n");
      out.write("\t\t\tf.k_max.focus();\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(f.k_max.value != \"\" && f.k_max.value > 30){\r\n");
      out.write("\t\t\talert(\"기 개수는 30을 넘을 수 없습니다\");\r\n");
      out.write("\t\t\tf.k_max.focus();\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(f.k_max.value != \"\" && f.k_max.value < 10){\r\n");
      out.write("\t\t\talert(\"기 개수는 10을 넘어야 합니다\");\r\n");
      out.write("\t\t\tf.k_max.focus();\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tf.submit();\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write(".form-custom{\r\n");
      out.write("\tmargin-bottom: 10px;\r\n");
      out.write("}\r\n");
      out.write(".sel-custom{\r\n");
      out.write("\theight: 34px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<title>W I S H</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!-- 상단 메뉴  -->   \r\n");
      out.write("   ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "search_bar.jsp", out, false);
      out.write("\r\n");
      out.write("   <div class=\"wrap\">\r\n");
      out.write("   \r\n");
      out.write("   <div class=\"col-md-3\">\r\n");
      out.write("   \t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "menu.jsp", out, false);
      out.write("\r\n");
      out.write("   \r\n");
      out.write("   </div>\r\n");
      out.write("   <div class=\"col-md-6\">\r\n");
      out.write("   \t\t<header>\r\n");
      out.write("\t\t\t\t<hgroup>\r\n");
      out.write("\t\t\t\t\t<h1> 글쓰기</h1>\r\n");
      out.write("\t\t\t\t</hgroup>\r\n");
      out.write("\t\t\t</header>\r\n");
      out.write("\t\t    <form action=\"ki_writeok.do\" method=\"post\" name=\"edit_form\" enctype=\"multipart/form-data\">\r\n");
      out.write("\t\t\t<br/>\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" name=\"u_idx\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${uvo.u_idx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" name=\"currpage\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${currpage }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">\r\n");
      out.write("\t\t \t\t<select class=\"form-control form-custom\" name=\"k_kind\">\r\n");
      out.write("\t\t\t\t\t\t<option value=\"0\" selected=\"selected\">기 카테고리를 선택하세요</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"취업\">취업</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"연애\">연애</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"출세\">출세</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"금전\">금전</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"건강\">건강</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"합격\">합격</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"기타\">기타</option>\r\n");
      out.write("\t\t\t\t</select>\r\n");
      out.write("\t\t      \t<textarea class=\"form-control form-custom\" name=\"k_content\" rows=\"15\" placeholder=\"글 내용을 입력하세요\" id=\"k_content\"></textarea>\r\n");
      out.write("\t\t      \t<input type=\"number\" min=\"10\" max=\"30\" placeholder=\"기 개수를 입력하세요 (10~30 숫자만 입력)\" name=\"k_max\" class=\"form-control form-custom\"/>\r\n");
      out.write("\t\t      \t<span style=\"font-size: 12px;float:right; \">기 크기는 이후 수정이 불가하므로 신중하게 입력해주세요</span><br/>\r\n");
      out.write("\t\t\t\t<label>이미지 (png, jpg, jpeg, gif만 가능)</label><input type=\"file\" class=\"form-control form-custom\" name=\"mf_image\" id=\"image\"  onchange=\"inputImage()\"/>\r\n");
      out.write("\t\t        <div class=\"action_btns\">\r\n");
      out.write("\t\t            <div class=\"one_half\" align=\"right\">\r\n");
      out.write("\t\t            <span class=\"counter\">0</span>/300&nbsp;\r\n");
      out.write("\t\t               <input type=\"button\" class=\"btn btn-default btn-lg\" value=\"글쓰기\" onclick=\"writee(this.form)\">\r\n");
      out.write("\t\t            </div>\r\n");
      out.write("\t\t        </div>\r\n");
      out.write("\t\t    </form>\r\n");
      out.write("   </div>\r\n");
      out.write("   <div class=\"col-md-3\">\r\n");
      out.write("   \r\n");
      out.write("   </div>\r\n");
      out.write("   </div>\r\n");
      out.write("    \r\n");
      out.write("<!-- footer -->\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery-1.11.2.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$('.form-custom').keyup(function(){\r\n");
      out.write("    var postLength = $(\"#k_content\").val().length;\r\n");
      out.write("    $('.counter').text(postLength);\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    if(postLength > 300){\r\n");
      out.write("        $('.btn').addClass('disabled');\r\n");
      out.write("    }else{\r\n");
      out.write("        $('.btn').removeClass('disabled');\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write(" });\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
